name: build
on:
  push:
    branches:
      - master
jobs:
  test:
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        node:
          - "14"
          - "12"
          - "10"
    name: Node.js ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm test
